services:
    kasimi.markreadconfirm.listener:
        class: kasimi\markreadconfirm\event\listener
        arguments:
            - @user
            - @template
            - @template_context
        tags:
            - { name: event.listener }
