services:
    o0johntam0o.codeboxplus.listener:
        class: o0johntam0o\codeboxplus\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    o0johntam0o.codeboxplus.controller:
        class: o0johntam0o\codeboxplus\controller\main
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@config'
            - '@auth'
            - '@request'
            - '@captcha.factory'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
